import type { Metadata } from "next";
import "./globals.css";
import type { ReactNode } from "react";
import AntdLayout from "./antd";
import Locale from "./i18n";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<AntdLayout>
					<Locale>{children}</Locale>
				</AntdLayout>
			</body>
		</html>
	);
}
